export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";

export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";

export const FETCH_PRODUCT_CART = "FETCH_PRODUCT_CART";
export const FETCH_PRODUCT_CART_SUCCESS = "FETCH_PRODUCT_CART_SUCCESS";
export const FETCH_PRODUCT_CART_FAILED = "FETCH_PRODUCT_CART_FAILED";

export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const UPDATE_QUANTITY_SUCCESS = "UPDATE_QUANTITY_SUCCESS";
export const UPDATE_SUM_QUANTITY_IN_CART = "UPDATE_SUM_QUANTITY_IN_CART";
export const UPDATE_SUB_QUANTITY_IN_CART = "UPDATE_SUB_QUANTITY_IN_CART";
export const UPDATE_SUM_QUANTITY_IN_CART_SUCCESS =
  "UPDATE_SUM_QUANTITY_IN_CART_SUCCESS";
// export const UPDATE_QUANTITY_IN_CART_SUCCESS = 'UPDATE_QUANTITY_IN_CART_SUCCESS';
export const UPDATE_SUBTRACTION_QUANTITY_IN_CART_SUCCESS =
  "UPDATE_SUBTRACTION_QUANTITY_IN_CART_SUCCESS";
export const UPDATE_QUANTITY_FAILED = "UPDATE_QUANTITY_FAILED";

export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const DELETE_PRODUCT_IN_CART_SUCCESS = "DELETE_PRODUCT_IN_CART_SUCCESS";
export const DELETE_PRODUCT_IN_CART_FAILED = "DELETE_PRODUCT_IN_CART_FAILED";

export const PAYMENT_PRODUCT = "PAYMENT_PRODUCT";
export const PAYMENT_PRODUCT_SUCCESS = "PAYMENT_PRODUCT_SUCCESS";
export const PAYMENT_PRODUCT_FAILED = "PAYMENT_PRODUCT_FAILED";
