export const TXT_ABOUT_US = "About Us";
export const TXT_CONTACT_US = "Contact Us";
export const TXT_BLOG = "Blog";
export const TXT_PROFILE = "Logout";
export const TXT_FACEBOOK = "Follow us on Facebook";
export const TXT_INSTAGRAM = "Follow us on Instagram";
export const TXT_ZALO = "Follow us on Zalo";
export const TXT_CONTENT_RECOMMEND =
  "Nếu bạn đang tìm kiếm một trang web để mua và bán hàng trực tuyến thì ShopingWithMe.vn là một sự lựa chọn hiệu quả dành cho bạn. Bản chất của ShopingWithMe là một social ecommerce platform - nền tảng trang web thương mại điện tử tích hợp mạng xã hội. Điều này cho phép người mua và người bán hàng dễ dàng tương tác, trao đổi thông tin về sản phẩm và chương trình khuyến mãi của shop. Nhờ nền tảng đó, việc mua bán trên ShopingWithMe trở nên nhanh chóng và đơn giản hơn. Bạn có thể trò chuyện trực tiếp với nhà bán hàng để hỏi trực tiếp về mặt hàng cần mua. Còn nếu bạn muốn tìm mua những dòng sản phẩm chính hãng, uy tín, ShopingWithMe chính là sự lựa chọn lí tưởng dành cho bạn. Đến với ShopingWithMe, cơ hội để trở thành một nhà bán hàng dễ dàng hơn bao giờ hết. Chỉ với vài thao tác trên ứng dụng, bạn đã có thể đăng bán ngay những sản phẩm của mình. Không những thế, các nhà bán hàng có thể tùy chọn các tính năng “Shop tạm nghỉ” hoặc tự tạo riêng cho mình một chương trình khuyến mãi để thu hút người mua với những sản phẩm có mức giá hấp dẫn. Khi đăng nhập tại ShopingWithMe Kênh người bán, bạn có thể dễ dàng phân loại sản phẩm, theo dõi đơn hàng, chăm sóc khách hàng và cập nhập ngay các hoạt động của shop";
export const TXT_TITLE_RECOMMEND =
  "SHOPPING-WITH-ME - MUA SẮM VÀ BÁN HÀNG ONLINE ĐƠN GIẢN, NHANH CHÓNG VÀ AN TOÀN";
export const TXT_CURRENCY_UNIT = "$";
export const TXT_SUB = "-";
export const TXT_SUM = "+";
export const TXT_TOTAL = "Tổng tiền";
export const TXT_PAY = "Thanh Toán";
export const TXT_PRODUCT = "Sản Phẩm";
export const TXT_PRICE = "Giá";
export const TXT_QUANTITY = "Số Lượng";
export const TXT_TOTAL_PRICE = "Tổng Cộng";
export const TXT_ACCOUNT = "Tài Khoản";
export const TXT_INPUT = "Nhập từ khóa";
export const TXT_REGISTER_ACCOUNT = "Đăng ký tài khoản";
export const TXT_AGREE_TERMS = "Đồng ý điều khoản";
export const TXT_REGISTER = "Đăng Ký";
export const TXT_LOGIN = "Đăng Nhập";
export const TXT_HAVE_ACCOUNT = "Đã có tài khoản ?";
export const TXT_LOGIN_TO_CONTINUE = "Đăng nhập để tiếp tục";
export const TXT_CONFIRM_PASSWORD_FAILED = "Mật khẩu không trùng khớp !";
